set_property SRC_FILE_INFO {cfile:G:/verilog/study/experiment4/uart/uart_top/uart_top.srcs/constrs_1/new/uart.xdc rfile:../../../uart_top.srcs/constrs_1/new/uart.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports rx]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports tx]
